[workspace]
# A separate workspace

[package]
edition      = "2024"
name         = "sea-orm-issues-1357"
publish      = false
rust-version = "1.85.0"
version      = "0.1.0"

[dependencies]
anyhow = "1"
serde  = "1"
tokio  = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }

[dependencies.sea-orm]
default-features = false
features         = ["macros", "runtime-tokio-native-tls", "sqlx-sqlite"]
path             = "../../"
