[package]
edition      = "2024"
name         = "sea-orm-quickstart"
publish      = false
rust-version = "1.85.0"
version      = "0.1.0"

[dependencies]
env_logger = { version = "0.11" }
log        = { version = "0.4" }

[dependencies.sea-orm-sync]
features = [
    "rusqlite",
    "debug-print",
    "entity-registry",
    "schema-sync",
]
path = "../../"
