[workspace]
# A separate workspace

[package]
name = "sea-orm-issues-86"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
sea-orm = { path = "../../", features = [ "sqlx-all", "runtime-tokio-native-tls", "debug-print" ] }
tokio = { version = "1", features = ["full"] }
env_logger = { version = "^0.9" }
log = { version = "^0.4" }
