[package]
edition      = "2024"
name         = "poem-example-api"
rust-version = "1.85.0"
version      = "0.1.0"

[dependencies]
dotenvy            = "0.15"
entity             = { path = "../entity" }
migration          = { path = "../migration" }
poem               = { version = "1.3.56", features = ["static-files"] }
serde              = { version = "1", features = ["derive"] }
tera               = "1.19.0"
tokio              = { version = "1.29.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[dependencies.sea-orm]
features = [
    "debug-print",
    "runtime-tokio-native-tls",
    # "sqlx-postgres",
    # "sqlx-mysql",
    "sqlx-sqlite",
]
path = "../../../" # remove this line in your own project
version = "~2.0.0-rc.30" # sea-orm version

[dev-dependencies]
poem-example-api = { path = ".", features = ["sqlite"] }

[features]
sqlite = ["sea-orm/sqlx-sqlite"]
