[workspace]
# A separate workspace

[package]
edition      = "2024"
name         = "sea-orm-issues-262"
publish      = false
rust-version = "1.85.0"
version      = "0.1.0"

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
sea-orm = { path = "../../", features = [
    "sqlx-all",
    "runtime-async-std-native-tls",
    "debug-print",
] }
