[package]
authors      = ["Sam Samai <sam@studio2pi.com.au>"]
edition      = "2024"
name         = "rocket-example-api"
publish      = false
rust-version = "1.85.0"
version      = "0.1.0"

[dependencies]
async-stream = { version = "0.3" }
async-trait = { version = "0.1" }
dto = { path = "../dto" }
entity = { path = "../entity" }
futures = { version = "0.3" }
futures-util = { version = "0.3" }
migration = { path = "../migration" }
rocket = { version = "0.5", features = ["json"] }
rocket-okapi-example-service = { path = "../service" }
rocket_cors = "0.6"
rocket_db_pools = "0.2"
rocket_dyn_templates = { version = "0.2", features = ["tera"] }
rocket_okapi = { version = "0.9", features = [
    "swagger",
    "rapidoc",
    "rocket_db_pools",
] }
serde = "1.0"
serde_json = { version = "1" }
tokio = "1.41"

[dependencies.sea-orm-rocket]
features = [
    "rocket_okapi",
] # enables rocket_okapi so to have open api features enabled
path = "../../../sea-orm-rocket/lib" # remove this line in your own project and use the version line
# version = "0.5"
