[workspace]
# A separate workspace

[package]
edition      = "2024"
name         = "sea-orm-issues-319"
publish      = false
rust-version = "1.85.0"
version      = "0.1.0"

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
sea-orm = { path = "../../", features = [
    "sqlx-mysql",
    "runtime-async-std-native-tls",
    "with-json",
    "with-chrono",
    "macros",
], default-features = false }
serde = { version = "1", features = ["derive"] }
