[package]
edition      = "2024"
name         = "sea-orm-tonic-example"
publish      = false
rust-version = "1.85.0"
version      = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "api", "entity", "migration"]

[dependencies]
tokio             = { version = "1.29", features = ["macros", "rt-multi-thread", "full"] }
tonic             = "0.9.2"
tonic-example-api = { path = "api" }

[[bin]]
name = "server"
path = "./src/server.rs"

[[bin]]
name = "client"
path = "./src/client.rs"