blank_issues_enabled: false
contact_links:
  - name: Q & A
    url: https://github.com/SeaQL/sea-orm/discussions/new?category=q-a
    about: Ask a question or look for help. Try to provide sufficient context, snippets to reproduce and error messages.
  - name: SeaQL Discord Server
    url: https://discord.com/invite/uCPdDXzbdv
    about: Join our Discord server to chat with others in the SeaQL community!
  - name: Professional Support
    url: https://github.com/sponsors/SeaQL
    about: Startup and Enterprise-tier sponsors enjoy direct communication with the SeaQL team and professional support for SeaORM usage, data engineering, and Rust development.