[package]
authors      = ["Sergio Benitez <sb@sergio.bz>", "Jeb Rosen <jeb@jebrosen.com>"]
description  = "Procedural macros for sea_orm_rocket."
edition      = "2024"
keywords     = ["rocket", "framework", "database", "pools"]
license      = "MIT OR Apache-2.0"
name         = "sea-orm-rocket-codegen"
readme       = "../README.md"
repository   = "https://github.com/SergioBenitez/Rocket/contrib/db_pools"
rust-version = "1.85.0"
version      = "0.6.0"

[lib]
proc-macro = true

[dependencies]
devise = "0.4"
quote  = "1"

[dev-dependencies]
rocket        = { version = "0.5.1", default-features = false }
trybuild      = "1"
version_check = "0.9"
