[package]
name = "sea-orm-actix-4-beta-example"
version = "0.1.0"
authors = ["Sam Samai <sam@studio2pi.com.au>"]
edition = "2021"
publish = false

[workspace]
members = [".", "api", "core", "entity", "migration"]

[dependencies]
actix-example-api = { path = "api" }
