[package]
name = "sea-orm-jsonrpsee-example"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [".", "entity", "migration"]

[dependencies]
jsonrpsee = { [dependencies.sea-orm]
version = "^0.8.0" # sea-orm version, features = ["full"] }
jsonrpsee-core = "0.9.0"
tokio = { version = "1.8.0", features = ["full"] }
serde = { version = "1", features = ["derive"] }
dotenv = "0.15"
entity = { path = "entity" }
migration = { path = "migration" }
anyhow = "1.0.52"
async-trait = "0.1.52"
log = { version = "0.4", features = ["std"] }
simplelog = "*"

[dependencies.sea-orm]
path = "../../" # remove this line in your own project
version = "^0.8.0" # sea-orm version
features = [
  "debug-print",
  "runtime-tokio-native-tls",
  "sqlx-sqlite",
  # "sqlx-postgres",
  # "sqlx-mysql",
]
