[workspace]
# A separate workspace

[package]
name = "sea-orm-issues-676"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sea-orm = { path = "../../", features = [ "sqlx-mysql", "runtime-async-std-native-tls" ]}
serde = { version = "^1" }
