[package]
edition      = "2024"
name         = "rocket-okapi-example-service"
rust-version = "1.85.0"
version      = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
entity = { path = "../entity" }

[dependencies.sea-orm]
features = [
    "runtime-tokio-native-tls",
    #    "sqlx-postgres",
    #    "sqlx-mysql",
    "sqlx-sqlite",
]
path = "../../../" # remove this line in your own project
version = "~2.0.0-rc.30" # sea-orm version

[dev-dependencies]
tokio = "1.41"
