[workspace]
# A separate workspace

[package]
authors      = ["Erik Rhodes <erik@space-nav.com>"]
edition      = "2024"
name         = "sea-orm-issues-630"
publish      = false
rust-version = "1.85.0"
version      = "0.1.0"

[dependencies]
serde = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }

[dependencies.sea-orm]
default-features = false
features = [
    "macros",
    "runtime-tokio-native-tls",
    "debug-print",
    "with-json",
    "with-chrono",
]
path = "../../"

[features]
default    = ["sqlx-mysql"]
sqlx-mysql = ["sea-orm/sqlx-mysql"]
