[package]
edition      = "2024"
name         = "jsonrpsee-example-api"
publish      = false
rust-version = "1.85.0"
version      = "0.1.0"

[dependencies]
anyhow         = "1.0.71"
async-trait    = "0.1.71"
dotenvy        = "0.15"
entity         = { path = "../entity" }
jsonrpsee      = { version = "0.18.2", features = ["full"] }
jsonrpsee-core = "0.18.2"
log            = { version = "0.4", features = ["std"] }
migration      = { path = "../migration" }
serde          = { version = "1", features = ["derive"] }
simplelog      = "0.12"
tokio          = { version = "1.29.1", features = ["full"] }

[dependencies.sea-orm]
features = [
    "debug-print",
    "runtime-tokio-native-tls",
    "sqlx-sqlite",
    # "sqlx-postgres",
    # "sqlx-mysql",
]
path = "../../../" # remove this line in your own project
version = "~2.0.0-rc.30" # sea-orm version
