[package]
name = "tonic-example-api"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
publish = false

[dependencies]
tonic = "0.9.2"
tokio = { version = "1.29", features = ["full"] }
entity = { path = "../entity" }
migration = { path = "../migration" }
prost = "0.11.9"
serde = "1.0"

[dependencies.sea-orm]
path = "../../../" # remove this line in your own project
version = "~2.0.0-rc.19" # sea-orm version
features = [
    "debug-print",
    "runtime-tokio-rustls",
    # "sqlx-mysql",
    # "sqlx-postgres",
    "sqlx-sqlite",
]

[build-dependencies]
tonic-build = "0.9.2"
