[package]
edition      = "2024"
name         = "tonic-example-api"
publish      = false
rust-version = "1.85.0"
version      = "0.1.0"

[dependencies]
entity    = { path = "../entity" }
migration = { path = "../migration" }
prost     = "0.11.9"
serde     = "1.0"
tokio     = { version = "1.29", features = ["full"] }
tonic     = "0.9.2"

[dependencies.sea-orm]
features = [
    "debug-print",
    "runtime-tokio-rustls",
    # "sqlx-mysql",
    # "sqlx-postgres",
    "sqlx-sqlite",
]
path = "../../../" # remove this line in your own project
version = "~2.0.0-rc.30" # sea-orm version

[build-dependencies]
tonic-build = "0.9.2"
