[workspace]
# A separate workspace

[package]
name = "sea-orm-issues-693"
version = "0.1.0"
authors = ["bleuse <raphael.bleuse@univ-grenoble-alpes.fr>"]
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.14", features = ["full"] }
anyhow = "1"
dotenvy = "0.15"
futures-util = "0.3"
serde = "1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dependencies.sea-orm]
path = "../../" # remove this line in your own project
features = ["runtime-tokio-rustls", "sqlx-mysql", "macros"]
default-features = false
