[workspace]
# A separate workspace

[package]
authors      = []
edition      = "2024"
name         = "sea-orm-issues-892"
publish      = false
rust-version = "1.85.0"
version      = "0.1.0"

[dependencies]
tokio = { version = "1.20.0", features = ["rt-multi-thread", "macros"] }

[dependencies.sea-orm]
default-features = false
features         = ["runtime-tokio-rustls", "tests-cfg", "sqlx-sqlite", "macros"]
path             = "../../"                                                       # remove this line in your own project
