[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }

[dependencies.sea-orm]
# path = "../../../" # remove this line in your own project
version = "^0.6.0"
features = [
  "macros",
  "debug-print",
  "runtime-actix-native-tls",
  "sqlx-mysql",
  # "sqlx-postgres",
  # "sqlx-sqlite",
]
default-features = false