[workspace]
# A separate workspace

[package]
edition      = "2024"
name         = "sea-orm-issues-324"
publish      = false
rust-version = "1.85.0"
version      = "0.1.0"

[dependencies]
sea-orm = { path = "../../", features = [
    "sqlx-mysql",
    "runtime-async-std-native-tls",
] }
