[package]
name = "sea-orm-rocket-example"
version = "0.1.0"
authors = ["Sam Samai <sam@studio2pi.com.au>"]
edition = "2021"
publish = false

[workspace]
members = [".", "api", "service", "entity", "migration"]

[dependencies]
rocket-example-api = { path = "api" }
