[package]
authors      = ["Aaron Leopold <aaronleopold1221@gmail.com>"]
edition      = "2024"
name         = "graphql-example-api"
publish      = false
rust-version = "1.85.0"
version      = "0.1.0"

[dependencies]
async-graphql      = { version = "7.0.17" }
async-graphql-axum = "7.0"
axum               = "0.8"
dotenvy            = "0.15.7"
entity             = { path = "../entity" }
migration          = { path = "../migration" }
tokio              = { version = "1.29", features = ["full"] }

[dependencies.sea-orm]
features = [
    "debug-print",
    "runtime-tokio-native-tls",
    # "sqlx-postgres",
    # "sqlx-mysql",
    "sqlx-sqlite",
]
path = "../../../" # remove this line in your own project
version = "~2.0.0-rc.30" # sea-orm version
