[package]
name = "graphql-example-api"
authors = ["Aaron Leopold <aaronleopold1221@gmail.com>"]
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
publish = false

[dependencies]
async-graphql = { version = "7.0.17" }
tokio = { version = "1.29", features = ["full"] }
axum = "0.8"
dotenvy = "0.15.7"
async-graphql-axum = "7.0"
entity = { path = "../entity" }
migration = { path = "../migration" }

[dependencies.sea-orm]
path = "../../../" # remove this line in your own project
version = "~2.0.0-rc.20" # sea-orm version
features = [
    "debug-print",
    "runtime-tokio-native-tls",
    # "sqlx-postgres",
    # "sqlx-mysql",
    "sqlx-sqlite",
]
