[package]
name = "graphql-example-api"
authors = ["Aaron Leopold <aaronleopold1221@gmail.com>"]
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
graphql-example-core = { path = "../core" }
tokio = { version = "1.0", features = ["full"] }
axum = "^0.5.1"
dotenvy = "0.15.0"
async-graphql-axum = "^4.0.6"
entity = { path = "../entity" }
migration = { path = "../migration" }
