[package]
edition      = "2024"
name         = "entity"
publish      = false
rust-version = "1.85.0"
version      = "0.1.0"

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
rocket = { version = "0.5", features = ["json"] }

[dependencies.sea-orm]
path    = "../../../"    # remove this line in your own project
version = "~2.0.0-rc.30" # sea-orm version
