[package]
authors      = ["Sam Samai <sam@studio2pi.com.au>"]
edition      = "2024"
name         = "actix-example-api"
publish      = false
rust-version = "1.85.0"
version      = "0.1.0"

[dependencies]
actix-files        = "0.6"
actix-http         = "3"
actix-rt           = "2.8"
actix-service      = "2"
actix-web          = "4"
dotenvy            = "0.15"
entity             = { path = "../entity" }
listenfd           = "1"
migration          = { path = "../migration" }
serde              = "1"
tera               = "1.19.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[dependencies.sea-orm]
features = [
    "debug-print",
    "runtime-tokio-native-tls",
    "sqlx-mysql",
    # "sqlx-postgres",
    # "sqlx-sqlite",
]
path = "../../../" # remove this line in your own project
version = "~2.0.0-rc.30" # sea-orm version

[dev-dependencies]
actix-example-api = { path = ".", features = ["sqlite"] }
tokio             = { version = "1.20.0", features = ["macros", "rt"] }

[features]
sqlite = ["sea-orm/sqlx-sqlite"]
