[package]
edition      = "2024"
name         = "service"
publish      = false
rust-version = "1.85.0"
version      = "0.1.0"

[dependencies]
sea-orm = { path = "../../../", default-features = false }

[dev-dependencies]
sea-orm = { path = "../../../", features = ["mock"] }
